### PR TITLE
4.0.1 troubles

### PR DESCRIPTION
**Pull request by boris-petrov**
@jakesjews Sorry I'm opening a PR but I couldn't send an email and contact you on Discord. :smile: Perhaps allow issues here on GitHub?

Otherwise - I updated to version 4.0.1 and hit 2 issues:

1) the "vendor" directory is missing from the NPM package and hence the plugin doesn't work at all:
    `Directory not found: /home/boris/project/node_modules/@eflexsystems/ember-cli-webfont/vendor`

2) if I manually add it and try building the project again, I get:
```
    File to import not found or unreadable
        ╷
    282 │ @import './iconfont';
        │         ^^^^^^^^^^^^
```

Even though I have `cssDest: 'app/styles/iconfont.scss',` in my `ember-cli-build`. Perhaps something else is wrong? Any ideas?

Thanks for your time on supporting the plugin!

### CODE REVIEW

**Comment by jakesjews** [comment]
oh my bad i didnt know anyone was using this ill turn on issues. ill add that vendor directory back in and see if that helps. whats weird is theres no vendor directory in our app and it still works but were on the latest ember-cli so maybe thats it

**Comment by jakesjews** [comment]
@boris-petrov what version of ember-cli are you on?

**Comment by boris-petrov** [comment]
@jakesjews thanks for the answer! I'm also using latest `ember-cli` (`4.6.0` right now). I'm not using Embroider though, are you? Also, what are the options that you're using `ember-cli-webfont` with? Perhaps something changed there.

**Comment by jakesjews** [comment]
@boris-petrov we're on embroider heres our config
```
    webfont: {
      path: 'public/fonts/icons',
      options: {
        files: ['**/*.svg'],
        dest: 'assets/icons/',
        fontName: 'eflex-icons',
        cssFontsUrl: 'icons/',
        types: ['woff2'],
        templateOptions: {
          classPrefix: 'icon-',
          baseSelector: '.icon'
        }
      }
    }
```
can you post your config in here and ill try it out on a fresh project

**Comment by jakesjews** [comment]
We aren't importing the iconfont directly either so maybe thats what the difference is

**Comment by boris-petrov** [comment]
That's one difference for sure. Here's my full conflig:

```js
webfont: {
  path: 'app/webfont-svg',
  options: {
    files: ['**/*.svg'],
    dest: 'assets/fonts/',
    fontName: 'iconfont',
    /* HACK:
     * Passing an explicit `cssDest` prevents `ember-cli-webfont` from
     * importing the output of `cssTemplate` into vendor.css.
     * This allows us to manually import the generated css in app.scss
     * and use @extends with iconfont classes
     */
    cssDest: 'app/styles/iconfont.scss',
    cssFontsUrl: config(emberEnvironment).rootURL + 'assets/fonts/',
    // TODO: rename the file back to `.hbs` when this is implemented:
    // https://github.com/ember-template-lint/ember-template-lint/issues/1728
    cssTemplate: 'app/webfont-svg/_template.css.handlebars1',
    templateOptions: {
      classPrefix: 'iconfont-',
      baseSelector: 'iconfont', // the documentation specifies that this should be a selector (e.g. `.iconfont`) but we need it this way (and it works)
    },
  },
}
```

As you see, there's a `HACK` comment which perhaps stopped working (maybe you've fixed the bug that we've been using) or something. :smile: But you can try that config in a new app (using `ember-cli-webfont` v3) and check how it works (like importing the font in `app.scss` and using the classes there). And then try the same config with v4.

Thanks! Let me know if you need more help.

**Comment by jakesjews** [comment]
@boris-petrov I published a new version that should work. You'll need to add `skipImport: true` to your config like
```
    webfont: {
      path: 'public/fonts/icons',
      skipImport: true,
      options: {
      }
    }
```

**Comment by boris-petrov** [comment]
@jakesjews thanks for the continued support!

So, I tried version 5.0.1. The `vendor` directory issue is fixed. However I still get the same error as before:

```
Build Error (PostcssCompiler) in /tmp/broccoli-82748qQRMJlSl2bVm/out-299-broccoli_merge_trees//app/styles/app.scss:282:9

File to import not found or unreadable
    ╷
282 │ @import './iconfont';
    │         ^^^^^^^^^^^^
    ╵
  /tmp/broccoli-82748qQRMJlSl2bVm/out-299-broccoli_merge_trees/app/styles/app.scss 282:9               @import
```

Indeed searching for `iconfont` leads to no results: `find /tmp/broccoli-82748qQRMJlSl2bVm/out-299-broccoli_merge_trees -name "*iconfont*"`. There is a `/tmp/broccoli-82748qQRMJlSl2bVm/out-299-broccoli_merge_trees/ember-cli-webfont.css` file however. Unfortunately using `@import '../../ember-cli-webfont';` instead of `@import './iconfont';` leads to an error:

```
Build Error (PostcssCompiler) in /tmp/broccoli-82748qQRMJlSl2bVm/out-299-broccoli_merge_trees//ember-cli-webfont.css:3:24

Silent comments aren't allowed in plain CSS.
  ╷
3 │     font-display: block; // https://github.com/vusion/webfonts-generator/pull/11
  │ ┌────────────────────────^
4 │ │   src: url("/project/assets/fonts/iconfont.eot?dbe209e3112ddc3e1210af13d5180cb5?#iefix") format("embedded-opentype"),
  │ └──^
  ╵
  /tmp/broccoli-82748qQRMJlSl2bVm/out-299-broccoli_merge_trees/ember-cli-webfont.css 3:24              @import
  /tmp/broccoli-82748qQRMJlSl2bVm/out-299-broccoli_merge_trees/app/styles/app.scss 282:9               @import
```

Any ideas what's going on?

**Comment by jakesjews** [comment]
@boris-petrov I [made a repo](https://github.com/jakesjews/webfont-example) using webfont and sass based on the config you put in above. I added `skipImport: true` and changed baseSelector from `'iconfont'` to `'.iconfont'` that might help narrow down what needs to be changed

**Comment by boris-petrov** [comment]
@jakesjews I think it's my mistake. When you told me about the `skipImport: true` setting, I thought that I had to remove the `HACK` thing with `cssDest` from my config. Leaving it in makes it work fine with version 5.0.1. Thanks for the help! I'll be sure to use the issues next time I have any troubles. :smile: Thank you for the time!

**Comment by jakesjews** [comment]
no problem glad to hear its working!

**Pull request closed without merging**
